suggestions_by_emotion = {
    "joy": [
        "It's great to hear you're feeling joyful! How about planning a fun activity with friends or family?",
        "Feeling joyful? Share your happiness by doing something kind for someone else!",
        "Joy is contagious! Spread it by organizing a game night with friends.",
        "Take a moment to appreciate what's making you happy and savor the feeling.",
        "Celebrate your joy by treating yourself to something you love, like your favorite dessert.",
        "Share your joy with others by posting about it on social media.",
        "Write down what’s making you happy and revisit it whenever you need a boost.",
        "Dance to your favorite song and let the joy flow through you!",
        "Plan a small celebration to honor your joyful mood.",
        "Call or text a friend to share your happiness with them.",
        "Take a walk outside and enjoy the beauty of nature.",
        "Create a playlist of songs that make you feel joyful and listen to it.",
        "Try a new hobby or activity that excites you.",
        "Bake or cook something delicious to share with others.",
        "Watch a feel-good movie or TV show that makes you smile.",
        "Write a gratitude list and reflect on the things that bring you joy.",
        "Take a photo of something that makes you happy and save it as a reminder.",
        "Plan a day trip or a weekend getaway to a place you love.",
        "Volunteer for a cause you care about and spread your joy to others.",
        "Paint, draw, or create something that expresses your happiness.",
        "Spend time with a pet or visit an animal shelter to share your joy with furry friends.",
        "Try a new recipe and enjoy the process of cooking and eating.",
        "Go for a bike ride and feel the wind in your hair.",
        "Write a letter to someone you care about and tell them why they make you happy.",
        "Take a yoga or meditation class to connect with your joyful energy.",
        "Visit a local park and have a picnic with friends or family.",
        "Start a journal and write about your joyful experiences.",
        "Take a bubble bath or do something relaxing to celebrate your happiness.",
        "Plan a surprise for someone you love to share your joy with them.",
        "Go stargazing and marvel at the beauty of the night sky.",
        "Try a new sport or physical activity that excites you.",
        "Visit a museum or art gallery and enjoy the creativity around you.",
        "Host a themed party or gathering with friends.",
        "Take a day off to do something you’ve always wanted to do.",
        "Learn something new, like a language or a musical instrument.",
        "Go to a concert or live performance and enjoy the energy of the crowd.",
        "Spend time gardening and connect with the earth.",
        "Write a poem or story inspired by your joyful mood.",
        "Take a scenic drive and enjoy the journey.",
        "Try a new restaurant or cuisine and savor the experience.",
        "Go to a comedy show or watch stand-up comedy online.",
        "Plan a DIY project and enjoy the process of creating something new.",
        "Take a photography walk and capture moments that bring you joy.",
        "Spend time with children and enjoy their laughter and energy.",
        "Go to a farmers' market and enjoy the fresh produce and vibrant atmosphere.",
        "Try a new workout or fitness class to boost your energy.",
        "Plan a movie marathon with your favorite films.",
        "Visit a botanical garden and enjoy the beauty of the flowers.",
        "Take a nap and recharge your energy for more joyful moments.",
        "Write down your dreams and goals and celebrate the progress you’ve made.",
    ],
    "sadness": [
        "It sounds like you're feeling down. How about watching a comedy movie or talking to a friend?",
        "When you're feeling sad, writing in a journal can help you process your emotions.",
        "Try going for a walk in nature to clear your mind and lift your spirits.",
        "Listening to uplifting music can help improve your mood.",
        "Reach out to a loved one and share how you're feeling.",
        "Write a letter to yourself expressing your feelings, and then read it back to gain perspective.",
        "Practice deep breathing exercises to calm your mind and body.",
        "Take a warm bath or shower to relax and soothe yourself.",
        "Try a mindfulness or meditation app to help you focus on the present moment.",
        "Spend time with a pet or visit an animal shelter to feel comforted.",
        "Read a book that inspires or uplifts you.",
        "Write down three things you're grateful for, no matter how small.",
        "Try a creative activity like painting, drawing, or crafting to express your emotions.",
        "Watch a nostalgic movie or TV show that brings back happy memories.",
        "Cook or bake something comforting and enjoy the process.",
        "Listen to a podcast or audiobook that interests you.",
        "Plan a small, achievable goal for the day to give yourself a sense of accomplishment.",
        "Write a list of things you enjoy and pick one to do today.",
        "Take a nap or rest if you're feeling emotionally drained.",
        "Spend time in a cozy spot with a blanket and a hot drink.",
        "Try a gentle yoga or stretching routine to relax your body.",
        "Write down your thoughts and feelings in a journal to release them.",
        "Call or text a friend and let them know you need someone to talk to.",
        "Watch funny videos or memes to lighten your mood.",
        "Go outside and sit in the sunlight for a few minutes.",
        "Write a letter to someone you trust about how you're feeling.",
        "Try a new hobby or activity to distract yourself and learn something new.",
        "Listen to calming music or nature sounds to relax.",
        "Write down positive affirmations and repeat them to yourself.",
        "Spend time with children and enjoy their innocence and energy.",
        "Volunteer for a cause you care about to shift your focus outward.",
        "Plan a small outing, like visiting a park or a café.",
        "Write a list of things you're looking forward to in the future.",
        "Try a guided meditation for sadness or grief.",
        "Spend time gardening or caring for plants to feel grounded.",
        "Watch a documentary about something you're curious about.",
        "Write a story or poem about your feelings to express them creatively.",
        "Take a day off to rest and recharge if you can.",
        "Spend time with friends or family who make you feel supported.",
        "Try a new recipe and enjoy the process of cooking and eating.",
        "Go for a drive and listen to your favorite music.",
        "Write down your dreams and goals to remind yourself of what matters to you.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Try a new workout or physical activity to release tension.",
        "Write a list of things that make you happy and revisit it when you're feeling down.",
        "Spend time in a library or bookstore and explore new books.",
        "Try a new skincare or self-care routine to pamper yourself.",
        "Write a letter to your future self about how you're feeling now.",
        "Spend time near water, like a lake or ocean, to feel calm.",
        "Try a new art form, like pottery or photography, to express yourself.",
    ],
    "anger": [
        "It seems like you're upset. Maybe try some deep breathing exercises or going for a walk.",
        "When you're angry, counting to 10 or taking a short break can help you calm down.",
        "Write down your feelings in a letter (you don’t have to send it) to release your emotions.",
        "Physical activity like running or yoga can help you channel your anger in a positive way.",
        "Try punching a pillow or screaming into it to release pent-up energy.",
        "Listen to calming music or nature sounds to help you relax.",
        "Take a cold shower or splash cold water on your face to cool down.",
        "Write a list of things that are making you angry and brainstorm solutions.",
        "Practice mindfulness or meditation to help you stay present and calm.",
        "Spend time with a pet or animal to feel comforted and grounded.",
        "Go for a brisk walk or run to release tension and clear your mind.",
        "Try a creative outlet like painting, drawing, or writing to express your anger.",
        "Talk to a trusted friend or family member about how you're feeling.",
        "Write down your anger triggers and reflect on how to avoid or manage them.",
        "Try progressive muscle relaxation to release tension in your body.",
        "Spend time in nature to help you feel more grounded and calm.",
        "Write a letter to the person or situation causing your anger (you don’t have to send it).",
        "Practice deep breathing by inhaling for 4 seconds, holding for 4 seconds, and exhaling for 6 seconds.",
        "Try a guided meditation for anger management.",
        "Spend time doing something you enjoy to distract yourself and shift your focus.",
        "Write down positive affirmations and repeat them to yourself.",
        "Try a new hobby or activity to channel your energy into something productive.",
        "Spend time with children and enjoy their innocence and energy.",
        "Go for a drive and listen to your favorite music to clear your mind.",
        "Write a list of things you're grateful for to shift your perspective.",
        "Try a new workout or fitness class to release pent-up energy.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Write a story or poem about your anger to express it creatively.",
        "Take a nap or rest if you're feeling emotionally drained.",
        "Spend time in a cozy spot with a blanket and a hot drink.",
        "Try a gentle yoga or stretching routine to relax your body.",
        "Write down your thoughts and feelings in a journal to release them.",
        "Call or text a friend and let them know you need someone to talk to.",
        "Watch funny videos or memes to lighten your mood.",
        "Go outside and sit in the sunlight for a few minutes.",
        "Write a letter to someone you trust about how you're feeling.",
        "Try a new hobby or activity to distract yourself and learn something new.",
        "Listen to calming music or nature sounds to relax.",
        "Write down positive affirmations and repeat them to yourself.",
        "Spend time with children and enjoy their innocence and energy.",
        "Volunteer for a cause you care about to shift your focus outward.",
        "Plan a small outing, like visiting a park or a café.",
        "Write a list of things you're looking forward to in the future.",
        "Try a guided meditation for anger or stress relief.",
        "Spend time gardening or caring for plants to feel grounded.",
        "Watch a documentary about something you're curious about.",
        "Write a story or poem about your feelings to express them creatively.",
        "Take a day off to rest and recharge if you can.",
        "Spend time with friends or family who make you feel supported.",
        "Try a new recipe and enjoy the process of cooking and eating.",
    ],
    "fear": [
        "It sounds like you're feeling anxious. Try focusing on your breathing or listening to calming music.",
        "When you're feeling fearful, talking to someone you trust can help ease your worries.",
        "Practice mindfulness or meditation to help calm your mind.",
        "Write down your fears to better understand and address them.",
        "Try a grounding exercise: Name 5 things you can see, 4 things you can touch, 3 things you can hear, 2 things you can smell, and 1 thing you can taste.",
        "Spend time with a pet or animal to feel comforted and grounded.",
        "Write a letter to your fear, expressing how it makes you feel and why you want to overcome it.",
        "Break down your fear into smaller, manageable steps and tackle them one at a time.",
        "Try a guided meditation for anxiety or fear.",
        "Spend time in nature to help you feel more grounded and calm.",
        "Write down positive affirmations and repeat them to yourself.",
        "Talk to a therapist or counselor about your fears and work on strategies to manage them.",
        "Try a creative outlet like painting, drawing, or writing to express your fears.",
        "Spend time with friends or family who make you feel supported and safe.",
        "Write a list of things you're grateful for to shift your perspective.",
        "Try a new hobby or activity to distract yourself and build confidence.",
        "Practice deep breathing by inhaling for 4 seconds, holding for 4 seconds, and exhaling for 6 seconds.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Write a story or poem about your fears to express them creatively.",
        "Take a nap or rest if you're feeling emotionally drained.",
        "Spend time in a cozy spot with a blanket and a hot drink.",
        "Try a gentle yoga or stretching routine to relax your body.",
        "Write down your thoughts and feelings in a journal to release them.",
        "Call or text a friend and let them know you need someone to talk to.",
        "Watch funny videos or memes to lighten your mood.",
        "Go outside and sit in the sunlight for a few minutes.",
        "Write a letter to someone you trust about how you're feeling.",
        "Try a new hobby or activity to distract yourself and learn something new.",
        "Listen to calming music or nature sounds to relax.",
        "Write down positive affirmations and repeat them to yourself.",
        "Spend time with children and enjoy their innocence and energy.",
        "Volunteer for a cause you care about to shift your focus outward.",
        "Plan a small outing, like visiting a park or a café.",
        "Write a list of things you're looking forward to in the future.",
        "Try a guided meditation for fear or stress relief.",
        "Spend time gardening or caring for plants to feel grounded.",
        "Watch a documentary about something you're curious about.",
        "Write a story or poem about your feelings to express them creatively.",
        "Take a day off to rest and recharge if you can.",
        "Spend time with friends or family who make you feel supported.",
        "Try a new recipe and enjoy the process of cooking and eating.",
        "Go for a drive and listen to your favorite music to clear your mind.",
        "Write down your dreams and goals to remind yourself of what matters to you.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Try a new workout or physical activity to release tension.",
        "Write a list of things that make you happy and revisit it when you're feeling down.",
        "Spend time in a library or bookstore and explore new books.",
        "Try a new skincare or self-care routine to pamper yourself.",
        "Write a letter to your future self about how you're feeling now.",
        "Spend time near water, like a lake or ocean, to feel calm.",
        "Try a new art form, like pottery or photography, to express yourself.",
    ],
    "surprise": [
        "Surprise can be overwhelming! Take a moment to process your feelings.",
        "When you're surprised, try to see it as an opportunity to learn something new.",
        "Share your surprise with someone and discuss how it made you feel.",
        "Take a deep breath and reflect on what this surprise means to you.",
        "Write down your thoughts and feelings about the surprise to process it better.",
        "Try a grounding exercise: Name 5 things you can see, 4 things you can touch, 3 things you can hear, 2 things you can smell, and 1 thing you can taste.",
        "Spend time with a pet or animal to feel comforted and grounded.",
        "Write a letter to yourself about the surprise and how it made you feel.",
        "Break down the surprise into smaller, manageable parts and tackle them one at a time.",
        "Try a guided meditation for processing unexpected events.",
        "Spend time in nature to help you feel more grounded and calm.",
        "Write down positive affirmations and repeat them to yourself.",
        "Talk to a trusted friend or family member about the surprise and how it affected you.",
        "Try a creative outlet like painting, drawing, or writing to express your feelings.",
        "Spend time with friends or family who make you feel supported and safe.",
        "Write a list of things you're grateful for to shift your perspective.",
        "Try a new hobby or activity to distract yourself and build confidence.",
        "Practice deep breathing by inhaling for 4 seconds, holding for 4 seconds, and exhaling for 6 seconds.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Write a story or poem about the surprise to express it creatively.",
        "Take a nap or rest if you're feeling emotionally drained.",
        "Spend time in a cozy spot with a blanket and a hot drink.",
        "Try a gentle yoga or stretching routine to relax your body.",
        "Write down your thoughts and feelings in a journal to release them.",
        "Call or text a friend and let them know you need someone to talk to.",
        "Watch funny videos or memes to lighten your mood.",
        "Go outside and sit in the sunlight for a few minutes.",
        "Write a letter to someone you trust about how you're feeling.",
        "Try a new hobby or activity to distract yourself and learn something new.",
        "Listen to calming music or nature sounds to relax.",
        "Write down positive affirmations and repeat them to yourself.",
        "Spend time with children and enjoy their innocence and energy.",
        "Volunteer for a cause you care about to shift your focus outward.",
        "Plan a small outing, like visiting a park or a café.",
        "Write a list of things you're looking forward to in the future.",
        "Try a guided meditation for processing unexpected events.",
        "Spend time gardening or caring for plants to feel grounded.",
        "Watch a documentary about something you're curious about.",
        "Write a story or poem about your feelings to express them creatively.",
        "Take a day off to rest and recharge if you can.",
        "Spend time with friends or family who make you feel supported.",
        "Try a new recipe and enjoy the process of cooking and eating.",
        "Go for a drive and listen to your favorite music to clear your mind.",
        "Write down your dreams and goals to remind yourself of what matters to you.",
        "Spend time in a quiet place and reflect on your feelings.",
        "Try a new workout or physical activity to release tension.",
        "Write a list of things that make you happy and revisit it when you're feeling down.",
        "Spend time in a library or bookstore and explore new books.",
        "Try a new skincare or self-care routine to pamper yourself.",
        "Write a letter to your future self about how you're feeling now.",
        "Spend time near water, like a lake or ocean, to feel calm.",
        "Try a new art form, like pottery or photography, to express yourself.",
    ],
    "love": [
        "It's wonderful to feel love! Share your feelings with someone special.",
        "Plan a romantic evening or a fun date to celebrate your feelings of love.",
        "Write a letter or poem expressing your love for someone.",
        "Do something kind for the person you love to show them how much you care.",
        "Spend quality time with the person you love, doing something you both enjoy.",
        "Write down what you love about someone and share it with them.",
        "Create a playlist of songs that remind you of love and listen to it.",
        "Cook or bake something special for the person you love.",
        "Plan a surprise for someone you love to make them feel appreciated.",
        "Write a gratitude list of things you love about your life.",
        "Spend time in nature and appreciate the beauty of the world around you.",
        "Volunteer for a cause you care about to spread love to others.",
        "Write a love letter to yourself, celebrating your strengths and qualities.",
        "Practice self-care by doing something that makes you feel loved and valued.",
        "Spend time with a pet or animal and enjoy their unconditional love.",
        "Watch a romantic movie or read a love story to immerse yourself in the feeling.",
        "Plan a picnic or outdoor activity with someone you love.",
        "Write down your favorite memories with the person you love and revisit them.",
        "Try a new activity or hobby with someone you love to create new memories.",
        "Spend time with friends or family who make you feel loved and supported.",
        "Write a list of things you love about yourself and read it when you need a boost.",
        "Practice mindfulness or meditation to connect with feelings of love and gratitude.",
        "Send a thoughtful text or message to someone you love, just to say you care.",
        "Plan a weekend getaway or a day trip with someone you love.",
        "Write a story or poem about love and share it with others.",
        "Spend time near water, like a lake or ocean, and reflect on the love in your life.",
        "Try a new recipe and enjoy the process of cooking and eating with someone you love.",
        "Go for a walk or hike with someone you love and enjoy the journey together.",
        "Write a list of things you're grateful for and share it with someone you love.",
        "Spend time gardening or caring for plants to nurture and grow love.",
        "Watch a sunset or sunrise and appreciate the beauty of the moment.",
        "Write a letter to someone you love, expressing how much they mean to you.",
        "Plan a game night or fun activity with friends or family you love.",
        "Spend time with children and enjoy their innocence and love.",
        "Try a new art form, like painting or photography, to express your feelings of love.",
        "Write down your dreams and goals and share them with someone you love.",
        "Spend time in a quiet place and reflect on the love in your life.",
        "Try a new workout or fitness class to boost your energy and feel good about yourself.",
        "Write a list of things that make you happy and revisit it when you need a reminder of love.",
        "Spend time in a library or bookstore and explore books about love and relationships.",
        "Try a new skincare or self-care routine to pamper yourself and feel loved.",
        "Write a letter to your future self about the love in your life now.",
        "Spend time near water, like a lake or ocean, to feel calm and connected to love.",
        "Try a new art form, like pottery or photography, to express yourself creatively.",
        "Plan a movie marathon with your favorite romantic films.",
        "Visit a botanical garden and enjoy the beauty of the flowers.",
        "Take a nap and recharge your energy for more loving moments.",
        "Write down your dreams and goals and celebrate the progress you’ve made.",
        "Spend time with friends or family who make you feel loved and supported.",
        "Try a new recipe and enjoy the process of cooking and eating with someone you love.",
    ],
}